models/Settings.php
<?php

namespace app\models;


/**
 * This is the model class for table "settings".
 *
 * @property int $id
 * @property string $key Ключ
 * @property string $value Значение
 * @property string $label Комментарий
 */
class Settings extends \yii\db\ActiveRecord
{
    /**
     * @const Тип "Тест". Настройка содержит строку
     */
    const TYPE_TEXT = 'text';

    /**
     * @const Тип "Чекбокс". Настройка содержит логическое значение (Да/Нет)
     */
    const TYPE_CHECKBOX = 'checkbox';

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'settings';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['key'], 'required'],
            [['label'], 'string'],
            [['key', 'value'], 'string', 'max' => 255],
            [['key'], 'unique'],
        ];
    }

//    /**
//     * @inheritdoc
//     */
//    public function beforeSave($insert)
//    {
//        if($this->type == self::TYPE_CHECKBOX){
//            if($this->value != '0')
//            {
//                $this->value = $this->value == 'on' ? '1' : '0';
//            }
//        }
//
//        return parent::beforeSave($insert);
//    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'key' => 'Ключ',
            'value' => 'Значение',
            'label' => 'Комментарий',
        ];
    }

    /**
     * Ищет запись в БД по ключу
     * @param string $key
     * @return null|static
     */
    public static function findByKey($key)
    {
        return self::findOne(['key' => $key]);
    }
}

controllers/SettingsController.php
<?php

namespace app\controllers;

use app\components\VkAPI;
use Yii;
use yii\web\Controller;
use app\models\Settings;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;

//use yii\web\ForbiddenHttpException;

/**
 * SettingsController implements the CRUD actions for Users model.
 */
class SettingsController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Отображет главную страницу настроек
     * @throws ForbiddenHttpException
     * @return mixed
     */
    public function actionIndex()
    {
        if(Yii::$app->user->identity->isSuperAdmin() == false){
            throw new ForbiddenHttpException();
        }

        $request = Yii::$app->request;

        $model = Yii::$app->user->identity;

        if ($request->isPost) {

            $data = $request->post();

            $model->load($request->post());
            $model->save();


            foreach ($data['Settings'] as $key => $value) {
                $setting = Settings::findByKey($key);

                if ($setting != null) {
                    $setting->value = $value;
                    $setting->save();
                    Yii::$app->session->setFlash('success', 'Настройки успешно сохранены');
                }
            }
        }
        $settings = Settings::find()->all();

        return $this->render('index', [
            'settings' => $settings,
            'model' => $model,
        ]);
    }

    public function actionGetAccountId()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;

        $response = VkAPI::getAccounts();

        if(isset($response['response']) == false){
            throw new NotFoundHttpException('Ошибка токена');
        }

        if(isset($response['response'][0])){
            return $response['response'][0]['account_id'];
        } else {
            throw new NotFoundHttpException('По токену не найдено рекламных кабинетов');
        }
    }
}

views/settings/index.php
<?php

/**
 * @var $this \yii\web\View
 * @var $settings \app\models\Settings[]
 */

$this->title = 'Настройки';

$accountId = \app\models\Settings::findByKey('account_id')->value;
if($accountId == null){
    $accountBalance = 0;
} else {
    $accountBalance = \app\components\VkAPI::getBalance($accountId);
}

?>


<div class="panel panel-inverse news-index">
    <div class="panel-heading">
        <!--        <div class="panel-heading-btn">-->
        <!--        </div>-->
        <h4 class="panel-title">Новости</h4>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-12">
                <?php if (count($settings) > 0) { ?>
                    <form method="post" class="form-horizontal form-bordered" style="padding: 0;">
                        <input type="hidden" name="<?= Yii::$app->request->csrfParam ?>"
                               value="<?= Yii::$app->request->csrfToken ?>">
                        <?php foreach ($settings as $setting): ?>
                            <div class="form-group">
                                <label for=""
                                       class="control-label col-md-2"><?= Yii::$app->formatter->asRaw($setting->label) ?></label>
                                <div class="col-md-10">
                                    <div class="col-md-8">
                                            <input name="Settings[<?= $setting->key ?>]" type="text"
                                                   value="<?= $setting->value ?>" class="form-control">
                                    </div>
                                </div>
                            </div>
                        <?php endforeach; ?>
                        <div class="form-group">
                            <label for="" class="control-label col-md-2">
                                Баланс кабинета: <?= Yii::$app->formatter->asCurrency($accountBalance, 'rub') ?>
                            </label>
                            <div class="col-md-10">
                                <div class="input-group">
                                    <button type="submit" style="margin-left: 15px;"
                                            class="btn btn-success btn-sm">Сохранить
                                    </button>
                                    <a style="margin-left: 15px;" href="https://oauth.vk.com/authorize?client_id=6651556&display=page&redirect_uri=https://oauth.vk.com/blank.html&scope=offline,groups,ads&response_type=token&v=5.37" class="btn btn-primary btn-sm" target="_blank">Получить ВК токен</a>
                                    <a id="account-id-button" href="<?=\yii\helpers\Url::toRoute(['settings/get-account-id'])?>" style="margin-left: 15px;" class="btn btn-info btn-sm">Получить ID рекламного кабинета</a>
                                    <input id="account-id-fld" type="text" disabled="disabled" class="form-control" style="display: none; width: 22%; height: 30px; float: right; cursor: pointer">
                                </div>
                            </div>
                        </div>
                    </form>
                <?php } else { ?>
                    <div class="note note-danger" style="margin: 15px;">
                        <h4><i class="fa fa-exclamation-triangle"></i> Настроек в базе данных не обнаружено!
                        </h4>
                        <p>
                            Убедитесь, что все миграции выполнены без ошибок
                        </p>
                    </div>
                <?php } ?>
            </div>
        </div>
    </div>
</div>

<?php

$script = <<< JS
$('#account-id-button').click(function(e){
    e.preventDefault();
    $.ajax({
        'method': 'GET',
        'url': $(this).attr('href'),
        success: function(response){
            $('#account-id-fld').slideDown('fast');
            $('#account-id-fld').val(response);  
        },
        error: function(error, error2){
          $('#account-id-fld').slideDown('fast');
          $('#account-id-fld').val(error.responseJSON.message);  
        }
    });
});
JS;

$this->registerJs($script, \yii\web\View::POS_READY);

?>